In [11]:
from einops import einsum
# from torch import einsum as torch_einsum
import torch
import numpy as np

In [5]:
w = np.arange(6).reshape(2, 3).astype(np.float32)
x = np.ones((3, 1), dtype=np.float32)

y = einsum(w, x, 'i j, j k -> i k')
print(y)

[[ 3.]
 [12.]]


In [ ]:
y = torch.einsum('ij,jk -> ik', torch.from_numpy(w), torch.from_numpy(x))
print(y)

tensor([[ 3.],
        [12.]])


### Simple dot product


In [19]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
result = torch.einsum('i, i -> ', a, b)
print(result)

tensor(32)


### Outer product


In [20]:
outer_product = torch.einsum('i, j -> i j', a, b)
print(outer_product)

tensor([[ 4,  5,  6],
        [ 8, 10, 12],
        [12, 15, 18]])


### Example Data


In [ ]:
w = torch.from_numpy(np.arange(9).reshape(3, 3).astype(np.float32))

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


### Diagonal


In [24]:
d = torch.einsum('i i -> i', w)
print(d)

tensor([0., 4., 8.])


In [ ]:
a = torch.from_numpy(np.arange(4).reshape(2, 2).astype(np.float32))
b = torch.from_numpy(np.arange(8).reshape(4, 2).astype(np.float32))
c = torch.einsum('i i, j i -> i j', a, b)
print(c)

tensor([[ 0.,  0.,  0.,  0.],
        [ 3.,  9., 15., 21.]])


### Trace


In [27]:
trace = torch.einsum('i i -> ', w)
print(trace)

tensor(12.)


### Transpose


In [28]:
transpose = torch.einsum('i j -> j i', w)
print(transpose)

tensor([[0., 3., 6.],
        [1., 4., 7.],
        [2., 5., 8.]])
